-- Read-only role and permissions
CREATE ROLE dblens_ro LOGIN PASSWORD 'dblens_ro_pw' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
REVOKE ALL ON DATABASE demo FROM PUBLIC;
GRANT CONNECT ON DATABASE demo TO dblens_ro;
GRANT USAGE ON SCHEMA public TO dblens_ro;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO dblens_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO dblens_ro;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA public FROM dblens_ro;
